name: Build and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: anatolygusev/gitlab-runner-yandex
    
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TARGETPLATFORM=linux/amd64
            GITLAB_RUNNER_VERSION=15.0.0
            DOCKER_MACHINE_VERSION=0.16.2
            DUMB_INIT_VERSION=1.2.5
            DOCKER_MACHINE_DRIVER_YANDEX_VERSION=0.1.35
