name: Build and Publish

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: anatolygusev/gitlab-runner-yandex:latest
          build-args:
            - TARGETPLATFORM=linux/amd64
            - GITLAB_RUNNER_VERSION=14.9.1
            - DOCKER_MACHINE_VERSION=0.16.2
            - DUMB_INIT_VERSION=1.2.2
            - DOCKER_MACHINE_DRIVER_YANDEX_VERSION=0.1.35
